name: Optionix CI/CD

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f code/backend/requirements.txt ]; then pip install -r code/backend/requirements.txt; fi
        
    - name: Run tests
      run: |
        cd code/backend
        python -m pytest

  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: code/frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd code/frontend
        npm ci
        
    - name: Run tests
      run: |
        cd code/frontend
        npm test
        
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./infrastructure
        push: false
        tags: optionix:latest
        
  build-and-deploy:
    needs: [backend-test, frontend-test, docker-build]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Build frontend
      run: |
        cd code/frontend
        npm ci
        npm run build
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f code/backend/requirements.txt ]; then pip install -r code/backend/requirements.txt; fi
        
    # Add deployment steps here based on your deployment strategy
